apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: podinfo-config
    behavior: merge
    literals:
      - uiColor="#2cfc03"
commonLabels:
  env: dev
patches:
  - path: patch-ingress.yaml
